export const LOADING = "LOADING";
export const CREATE_NEW_CONTACT = "CREATE_NEW_CONTACT";
export const GET_ALL_USERS_DETAIL = "GET_ALL_USERS_DETAIL";
export const DELETE_USER = "DELETE_USER";
export const SEND_NOTIFICATION_SUCCESS = "SEND_NOTIFICATION_SUCCESS";
export const SEND_NOTIFICATION_ERROR = "SEND_NOTIFICATION_ERROR";
